[window]
# window padding {px}
padding.x = 16
padding.y = 16

[font]
size = 12.0

[colors]
[colors.primary]
background = "#000000"
foreground = "#FFFFFF"
dim_foreground = "#333333"
bright_foreground = "#9A9A9A"

[colors.cursor]
text = "#000000"
cursor = "#FFFFFF"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#FFFFFF"

[colors.selection]
text = "CellForeground"
background = "#888888"

[colors.search.matches]
foreground = "#FFFFFF"
background = "#000000"

[colors.search.focused_match]
foreground = "#FFFFFF"
background = "#000000"

[colors.footer_bar]
foreground = "#FFFFFF"
background = "#000000"

[colors.hints.start]
foreground = "#FFFFFF"
background = "#000000"

[colors.hints.end]
foreground = "#FFFFFF"
background = "#000000"

[colors.normal]
black = "#333333"
red = "#FFFFFF"
green = "#9A9A9A"
yellow = "#FFFFFF"
blue = "#FFFFFF"
magenta = "#FFFFFF"
cyan = "#FFFFFF"
white = "#FFFFFF"

[colors.bright]
black = "#9A9A9A"
red = "#FFFFFF"
green = "#9A9A9A"
yellow = "#FFFFFF"
blue = "#FFFFFF"
magenta = "#FFFFFF"
cyan = "#FFFFFF"
white = "#FFFFFF"

[[colors.indexed_colors]]
index = 16
color = "#FFFFFF"

[[colors.indexed_colors]]
index = 17
color = "#FFFFFF"